import { MessageSquare, Mail, Share2, Phone, Star, BarChart3, Users, Target, Bot, FileText, Bell, Calendar, Globe, TrendingUp, Megaphone, Shield, Zap, Clock } from "lucide-react";

export interface AutomationItem {
  id: string;
  name: string;
  description: string;
  category: string;
  icon: React.ComponentType<{ className?: string }>;
  setupFields: { label: string; placeholder: string; type: "text" | "textarea" | "select"; options?: string[] }[];
}

export const CATEGORIES = ["All", "Lead Gen", "Email", "Social", "Voice", "Reviews", "Analytics"];

export const AUTOMATIONS: AutomationItem[] = [
  { id: "1", name: "Website Lead Capture Bot", description: "AI chatbot that greets visitors, answers FAQs, and captures contact details 24/7.", category: "Lead Gen", icon: MessageSquare, setupFields: [{ label: "Business Name", placeholder: "Acme Corp", type: "text" }, { label: "Services Offered", placeholder: "List your main services", type: "textarea" }] },
  { id: "2", name: "Facebook Lead Ads Responder", description: "Instantly follows up with every Facebook lead ad submission via email and SMS.", category: "Lead Gen", icon: Target, setupFields: [{ label: "Business Name", placeholder: "Acme Corp", type: "text" }, { label: "Follow-up Message", placeholder: "Hi! Thanks for reaching out...", type: "textarea" }] },
  { id: "3", name: "Landing Page AI Builder", description: "Generates high-converting landing pages for your campaigns automatically.", category: "Lead Gen", icon: Globe, setupFields: [{ label: "Campaign Goal", placeholder: "e.g. Book a free consultation", type: "text" }, { label: "Target Audience", placeholder: "Small business owners in Austin", type: "text" }] },
  { id: "4", name: "Welcome Email Sequence", description: "Sends a personalized 5-part welcome series to every new lead or customer.", category: "Email", icon: Mail, setupFields: [{ label: "Business Name", placeholder: "Acme Corp", type: "text" }, { label: "Tone of Voice", placeholder: "Professional, Friendly, Casual", type: "text" }] },
  { id: "5", name: "Abandoned Cart Recovery", description: "Automatically emails customers who left items in their cart with a personalized reminder.", category: "Email", icon: Mail, setupFields: [{ label: "Store Name", placeholder: "Your online store name", type: "text" }, { label: "Discount Offer", placeholder: "e.g. 10% off", type: "text" }] },
  { id: "6", name: "Re-Engagement Campaign", description: "Wins back inactive customers with a smart, timed email sequence.", category: "Email", icon: Bell, setupFields: [{ label: "Business Name", placeholder: "Acme Corp", type: "text" }, { label: "Special Offer", placeholder: "e.g. Come back for 20% off", type: "textarea" }] },
  { id: "7", name: "Monthly Newsletter AI", description: "Generates and sends a professional newsletter with industry news and your updates.", category: "Email", icon: FileText, setupFields: [{ label: "Business Name", placeholder: "Acme Corp", type: "text" }, { label: "Industry", placeholder: "Real Estate", type: "text" }] },
  { id: "8", name: "Instagram Content AI", description: "Creates, captions, and schedules Instagram posts tailored to your brand.", category: "Social", icon: Share2, setupFields: [{ label: "Brand Name", placeholder: "Acme Corp", type: "text" }, { label: "Brand Voice", placeholder: "Describe your style", type: "textarea" }] },
  { id: "9", name: "LinkedIn Post Generator", description: "Writes thought-leadership posts for LinkedIn on autopilot.", category: "Social", icon: Users, setupFields: [{ label: "Your Name/Title", placeholder: "John Smith, CEO", type: "text" }, { label: "Topics", placeholder: "AI, business growth, leadership", type: "text" }] },
  { id: "10", name: "Social Media Comment Responder", description: "Automatically replies to comments on your social posts with on-brand responses.", category: "Social", icon: MessageSquare, setupFields: [{ label: "Brand Name", placeholder: "Acme Corp", type: "text" }, { label: "Response Tone", placeholder: "Friendly and helpful", type: "text" }] },
  { id: "11", name: "TikTok Script Writer", description: "Generates viral TikTok video scripts based on trending topics in your niche.", category: "Social", icon: Megaphone, setupFields: [{ label: "Business Niche", placeholder: "e.g. Fitness coaching", type: "text" }, { label: "Target Audience", placeholder: "Young professionals", type: "text" }] },
  { id: "12", name: "AI Phone Receptionist", description: "Answers incoming calls, takes messages, and routes to the right team member.", category: "Voice", icon: Phone, setupFields: [{ label: "Business Name", placeholder: "Acme Corp", type: "text" }, { label: "Business Hours", placeholder: "Mon-Fri 9am-5pm", type: "text" }] },
  { id: "13", name: "Appointment Booking Bot", description: "Handles phone-based appointment scheduling and sends confirmations.", category: "Voice", icon: Calendar, setupFields: [{ label: "Business Name", placeholder: "Acme Corp", type: "text" }, { label: "Services", placeholder: "List bookable services", type: "textarea" }] },
  { id: "14", name: "Outbound Call AI", description: "Makes follow-up calls to leads with a natural-sounding AI voice agent.", category: "Voice", icon: Phone, setupFields: [{ label: "Business Name", placeholder: "Acme Corp", type: "text" }, { label: "Call Script Outline", placeholder: "Key talking points", type: "textarea" }] },
  { id: "15", name: "Google Review Responder", description: "Crafts thoughtful, on-brand replies to every Google review — positive or negative.", category: "Reviews", icon: Star, setupFields: [{ label: "Business Name", placeholder: "Acme Corp", type: "text" }, { label: "Brand Tone", placeholder: "Warm and professional", type: "text" }] },
  { id: "16", name: "Yelp Review Manager", description: "Monitors and responds to Yelp reviews automatically with your brand voice.", category: "Reviews", icon: Star, setupFields: [{ label: "Business Name", placeholder: "Acme Corp", type: "text" }, { label: "Brand Tone", placeholder: "Friendly and apologetic when needed", type: "text" }] },
  { id: "17", name: "Review Request Sender", description: "Automatically asks happy customers to leave a review after their purchase or visit.", category: "Reviews", icon: Shield, setupFields: [{ label: "Business Name", placeholder: "Acme Corp", type: "text" }, { label: "Review Platform URL", placeholder: "https://g.page/...", type: "text" }] },
  { id: "18", name: "Weekly Performance Report", description: "AI-generated weekly summary of leads, sales, and marketing metrics.", category: "Analytics", icon: BarChart3, setupFields: [{ label: "Business Name", placeholder: "Acme Corp", type: "text" }, { label: "Key Metrics", placeholder: "Revenue, leads, website traffic", type: "text" }] },
  { id: "19", name: "Competitor Analysis AI", description: "Monitors competitor activity and sends you a monthly intelligence report.", category: "Analytics", icon: TrendingUp, setupFields: [{ label: "Your Business", placeholder: "Acme Corp", type: "text" }, { label: "Competitors", placeholder: "List 2-3 competitors", type: "textarea" }] },
  { id: "20", name: "Customer Insights Dashboard", description: "AI-powered dashboard that surfaces trends in customer behavior and sentiment.", category: "Analytics", icon: Bot, setupFields: [{ label: "Business Name", placeholder: "Acme Corp", type: "text" }, { label: "Data Sources", placeholder: "e.g. Reviews, social, email", type: "text" }] },
  { id: "21", name: "SEO Content Writer", description: "Writes SEO-optimized blog posts and web content based on trending keywords.", category: "Lead Gen", icon: Zap, setupFields: [{ label: "Business Name", placeholder: "Acme Corp", type: "text" }, { label: "Target Keywords", placeholder: "e.g. plumber Austin TX", type: "text" }] },
  { id: "22", name: "Invoice Follow-Up AI", description: "Sends polite automated reminders for unpaid invoices.", category: "Email", icon: Clock, setupFields: [{ label: "Business Name", placeholder: "Acme Corp", type: "text" }, { label: "Payment Terms", placeholder: "Net 30", type: "text" }] },
];
